US_TARGET_CITIES = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "Austin",
    "San Jose",
    "Miami",
    "Seattle",
    "Denver",
    "Atlanta",
    "Boston",
    "Nashville",
    "Las Vegas",
    "Portland",
    "Charlotte",
]
